// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqbkrtxlgyosjubwnpwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxYmtydHhsZ3lvc2p1YnducHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODMwNTYsImV4cCI6MjA3MTk1OTA1Nn0.x4ULyaXNyxduHF47GY6elmLijCAyKbVc7MieJR7qqDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});